version: '3.8'

services:
  fastapi:
    build: .
    container_name: Plexicus-vulnerabilities-app
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
